services:
  - type: web
    name: kizuna
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py "app:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: kizuna-db
          property: connectionString

databases:
  - name: kizuna-db
    databaseName: kizuna
    user: kizuna
